"""The HomeSync score and sound design, composed in code.

Nothing here is sampled, licensed or generated by a model: every sound is
synthesised from a seeded formula, so the score renders identically every time
and nobody else's music is in it.

  python3 audio/score.py [--out work/audio]

Writes music.wav (the music-only version), sfx.wav, and mix.wav, all 48 kHz
stereo, 30.000 s, with every scene change and every on-screen action at the
sample the picture puts it on.

The musical idea follows the film: under the problem, a pluck answered by its
own late copies — an echo you can hear — and from the moment HomeSync appears
the copies are gone and the same figure plays clean, on one time.
"""

import argparse
import os

import numpy as np

SR = 48_000
BPM = 96
BEAT = 60 / BPM
DURATION = 48 * BEAT  # 30.0 s
N = int(round(DURATION * SR))
RNG = np.random.default_rng(20251004)

# Scene changes, in beats — must match src/shared/beats.js.
SCENE_BEATS = [0, 3, 6, 10, 13, 17, 21, 25, 29, 35, 39, 43, 48]
# Changes that are one continuous camera move rather than a new scene get no
# whoosh: 1→2 (the camera rises over the same floor) and 7→8 (the same
# diagram pulls back).
NO_WHOOSH = {3, 25}
WHOOSH_BEATS = [b for b in SCENE_BEATS[1:-1] if b not in NO_WHOOSH]
# Real on-screen actions (seconds): all three play buttons pressed together,
# the scan completing, the tap on "Enable audio & join", the room appearing
# with "this device", Enter in the terminal.
PRESSES = [1 * BEAT]
SCAN_DONE = 14 * BEAT  # 8.750 s
TAP = 15 * BEAT  # 9.375 s
JOINED = 16 * BEAT  # 10.000 s
ENTER = 40 * BEAT  # 25.000 s
# The house: the three bars touch the plane of T together.
HOUSE_ARRIVAL = 34 * BEAT  # 21.250 s

HERO = 10 * BEAT  # 6.25 s: HomeSync appears; the echo stops


def t_axis(n=N):
    return np.arange(n) / SR


def midi_hz(m):
    return 440.0 * 2 ** ((m - 69) / 12)


def fft_filter(x, low=None, high=None, slope=6.0):
    """Zero-phase band filter in the frequency domain, with soft shoulders."""
    spectrum = np.fft.rfft(x, axis=0)
    freqs = np.fft.rfftfreq(x.shape[0], 1 / SR)
    gain = np.ones_like(freqs)
    if high is not None:
        gain *= 1 / np.sqrt(1 + (freqs / high) ** (2 * slope / 6))
    if low is not None:
        safe = np.maximum(freqs, 1e-3)
        gain *= 1 / np.sqrt(1 + (low / safe) ** (2 * slope / 6))
    if x.ndim == 2:
        gain = gain[:, None]
    return np.fft.irfft(spectrum * gain, n=x.shape[0], axis=0)


def env_adsr(n, a, d, s, r, total):
    """Attack, decay, sustain level, release — all in seconds — over `total`."""
    t = np.arange(n) / SR
    e = np.where(t < a, t / max(a, 1e-6), 1.0)
    e = np.where((t >= a) & (t < a + d), 1 - (1 - s) * (t - a) / max(d, 1e-6), e)
    e = np.where((t >= a + d) & (t < total), s, e)
    e = np.where(t >= total, s * np.exp(-(t - total) / max(r, 1e-6) * 4), e)
    return e


def place(buffer, sound, at_seconds, gain=1.0):
    start = int(round(at_seconds * SR))
    if start >= buffer.shape[0]:
        return
    end = min(buffer.shape[0], start + sound.shape[0])
    if start < 0:
        sound = sound[-start:]
        start = 0
        end = min(buffer.shape[0], sound.shape[0])
    buffer[start:end] += sound[: end - start] * gain


def stereo(mono, pan=0.0):
    left = np.cos((pan + 1) * np.pi / 4)
    right = np.sin((pan + 1) * np.pi / 4)
    return np.stack([mono * left, mono * right], axis=1)


# --- instruments -------------------------------------------------------------


def pad_voice(freq, seconds, brightness=0.35):
    """A soft pad: detuned sine partials, slow in, slow out."""
    n = int(seconds * SR) + SR
    t = t_axis(n)
    out = np.zeros(n)
    for detune in (-0.0035, 0.0, 0.0041):
        f = freq * (1 + detune)
        for k, amp in ((1, 1.0), (2, brightness), (3, brightness * 0.45), (4, brightness * 0.2)):
            out += amp * np.sin(2 * np.pi * f * k * t + RNG.uniform(0, 2 * np.pi))
    out *= env_adsr(n, 0.9, 0.6, 0.8, 0.9, seconds)
    return out / 6


def pluck(freq, seconds=1.2, damping=0.996):
    """Karplus–Strong string from seeded noise."""
    n = int(seconds * SR)
    period = max(2, int(round(SR / freq)))
    buf = RNG.uniform(-1, 1, period)
    out = np.empty(n)
    for i in range(n):
        out[i] = buf[i % period]
        buf[i % period] = damping * 0.5 * (buf[i % period] + buf[(i + 1) % period])
    out *= np.exp(-np.arange(n) / SR * 2.2)
    return fft_filter(out, high=3200)


def bass_note(freq, seconds):
    n = int(seconds * SR)
    t = t_axis(n)
    out = np.sin(2 * np.pi * freq * t) + 0.18 * np.sin(2 * np.pi * freq * 2 * t)
    return out * env_adsr(n, 0.02, 0.25, 0.65, 0.2, seconds * 0.85)


def soft_kick():
    n = int(0.32 * SR)
    t = t_axis(n)
    f = 46 + 70 * np.exp(-t * 28)
    phase = 2 * np.pi * np.cumsum(f) / SR
    return np.sin(phase) * np.exp(-t * 11)


def hat():
    n = int(0.06 * SR)
    noise = RNG.uniform(-1, 1, n)
    return fft_filter(noise, low=6500, high=11000) * np.exp(-np.arange(n) / SR * 70)


def reverb(x, seconds=2.2, mix=0.22):
    """Convolution with a seeded, exponentially decaying, slightly darkened tail."""
    n = int(seconds * SR)
    decay = np.exp(-np.arange(n) / SR * (6.9 / seconds))
    ir = np.stack([RNG.normal(0, 1, n) * decay, RNG.normal(0, 1, n) * decay], axis=1)
    ir = fft_filter(ir, low=180, high=6000)
    ir /= np.sqrt(np.sum(ir**2, axis=0, keepdims=True))
    size = x.shape[0] + n
    wet = np.stack(
        [np.fft.irfft(np.fft.rfft(x[:, c], size) * np.fft.rfft(ir[:, c], size), size)[: x.shape[0]] for c in (0, 1)],
        axis=1,
    )
    return x * (1 - mix) + wet * mix * 1.8


# --- the music ----------------------------------------------------------------

# One chord per bar (12 bars). D major, unhurried: I – vi – IV – V, twice,
# then lifted for the house, and home.
CHORDS = [
    [50, 57, 62, 66, 69],  # D
    [47, 54, 59, 62, 66],  # Bm
    [43, 50, 55, 59, 62],  # G
    [45, 52, 57, 61, 64],  # A
    [50, 57, 62, 66, 69],  # D
    [47, 54, 59, 62, 66],  # Bm
    [43, 50, 55, 59, 66],  # Gmaj7
    [45, 52, 57, 61, 64],  # A
    [47, 54, 59, 62, 69],  # Bm add
    [43, 50, 55, 62, 67],  # G
    [45, 52, 57, 64, 69],  # A sus feel
    [50, 57, 62, 66, 69],  # D
]
BAR = 4 * BEAT

# The figure the pluck plays: scale degrees over each bar's chord, an eighth apart.
FIGURE = [0, 2, 3, 2, 4, 3, 2, 3]


def compose_music():
    music = np.zeros((N + SR * 3, 2))

    # Pads: every bar, entering softly. The first bar starts already sounding,
    # so the opening frame has music under it rather than silence.
    for bar, chord in enumerate(CHORDS):
        start = bar * BAR
        for i, note in enumerate(chord[1:]):
            voice = pad_voice(midi_hz(note), BAR + 0.4, brightness=0.28 if bar < 8 else 0.38)
            place(music, stereo(voice, pan=(i - 1.5) * 0.35), max(0, start - (0.5 if bar == 0 else 0.15)), 0.33)

    # Bass from the moment HomeSync arrives, on the bar's root.
    for bar, chord in enumerate(CHORDS):
        start = bar * BAR
        if start + BAR <= HERO:
            continue
        for half in (0, 2):
            at = start + half * BEAT
            if at < HERO:
                continue
            place(music, stereo(bass_note(midi_hz(chord[0] - 12), 2 * BEAT)), at, 0.30)

    # The figure: eighth notes. Before HERO each note is followed by two late,
    # quieter copies — the echo the film is about. After HERO, played clean.
    eighth = BEAT / 2
    for bar, chord in enumerate(CHORDS):
        scale = sorted(set(n % 12 for n in chord))
        for step, degree in enumerate(FIGURE):
            at = bar * BAR + step * eighth
            if at >= DURATION - 0.6:
                continue
            root = chord[2] + 12
            pitch = root + [0, 2, 4, 7, 9, 12][degree % 6]
            if pitch % 12 not in scale and (pitch - 1) % 12 in scale:
                pitch -= 1
            note = pluck(midi_hz(pitch), 1.0)
            level = 0.20 if at < HERO else 0.24
            place(music, stereo(note, pan=0.25 * np.sin(step)), at, level)
            if at < HERO:
                place(music, stereo(note, pan=-0.6), at + 0.071, level * 0.55)
                place(music, stereo(note, pan=0.6), at + 0.163, level * 0.38)

    # A pulse from the mechanism onward: a soft kick on every beat, quiet hats
    # on the off-beats. Low — this is a bed, not a track.
    for b in range(10, 46):
        at = b * BEAT
        place(music, stereo(soft_kick()), at, 0.32 if b >= 19 else 0.22)
        if b >= 19:
            place(music, stereo(hat(), pan=0.3), at + BEAT / 2, 0.035)

    music = reverb(music[: N + SR * 3])[:N]

    # Ease in over the first beat and out over the last bar, so neither end is
    # a hard edge.
    t = t_axis(N)
    fade = np.minimum(1, t / 0.4) * np.clip((DURATION - t) / 1.6, 0, 1) ** 0.7
    return music * fade[:, None]


# --- sound design -------------------------------------------------------------


def whoosh(seconds=0.42):
    """Short, soft air: band-passed noise swept up then down, peaking at the cut."""
    n = int(seconds * SR)
    noise = RNG.normal(0, 1, n)
    t = np.arange(n) / n
    shape = np.sin(np.pi * t) ** 2.4
    # Two overlapping bands, the upper one later, for a sweep without a boom.
    # Steep shoulders. At 6 dB per octave the noise leaked all the way down to
    # 20 Hz, which is a boom under every cut; at 24 it stays in its band.
    low = fft_filter(noise, low=700, high=2600, slope=24) * shape
    high = fft_filter(noise, low=2400, high=7000, slope=24) * np.sin(np.pi * np.clip(t * 1.15 - 0.1, 0, 1)) ** 3
    return low * 0.7 + high * 0.5


def click():
    """A small, dry tick for a press."""
    n = int(0.045 * SR)
    t = np.arange(n) / SR
    body = np.sin(2 * np.pi * 2200 * t) * np.exp(-t * 160)
    snap = fft_filter(RNG.uniform(-1, 1, n), low=2500, high=6500, slope=24) * np.exp(-t * 300)
    # A millisecond of attack: an instant onset is a broadband spike, which
    # reads as a pop across the whole spectrum rather than a tick in its band.
    return (body * 0.6 + snap * 0.5) * np.minimum(1, t / 0.001)


def chime():
    """The instant arriving everywhere: one soft, bright tone."""
    n = int(0.9 * SR)
    t = np.arange(n) / SR
    tone = sum(a * np.sin(2 * np.pi * f * t) for f, a in ((1760, 1.0), (2640, 0.35), (3520, 0.18)))
    return tone * np.exp(-t * 5.5) * np.minimum(1, t / 0.004)


def compose_sfx():
    sfx = np.zeros((N, 2))
    # A whoosh on every scene change except the first frame and the last.
    # The peak of the swell sits on the cut itself.
    for b in WHOOSH_BEATS:
        w = whoosh()
        place(sfx, stereo(w), b * BEAT - 0.42 * 0.5, 1.0)
    for at in PRESSES + [SCAN_DONE, TAP, JOINED, ENTER]:
        place(sfx, stereo(click()), at, 1.0)
    place(sfx, stereo(chime()), HOUSE_ARRIVAL, 0.8)
    # Nothing in the effects belongs below 300 Hz or above 9 kHz: that is boom
    # and hiss, and the music already owns the low end.
    return fft_filter(sfx, low=300, high=9000, slope=24)


# --- mixing and measurement ----------------------------------------------------


def rms_db(x):
    return 20 * np.log10(np.sqrt(np.mean(x**2)) + 1e-12)


def band(x, low, high):
    return fft_filter(x, low=low, high=high, slope=24)


def balance_sfx(music, sfx, margin_db=2.5, cap_db=-24.0):
    """Sets each effect just above the music *in its own band*, with a cap.

    Each event is measured against the music in the same frequency range over
    the same stretch of time, then scaled to sit `margin_db` above it — loud
    enough to land, never louder than the music overall, and capped so no
    single effect can get harsh.
    """
    out = np.zeros_like(sfx)
    events = [(b * BEAT - 0.21, 0.42, 700, 7000) for b in WHOOSH_BEATS]
    events += [(at, 0.045, 2000, 6500) for at in PRESSES + [SCAN_DONE, TAP, JOINED, ENTER]]
    events += [(HOUSE_ARRIVAL, 0.9, 1500, 4000)]
    music_mono = music.mean(axis=1)
    for start, length, low, high in events:
        a = max(0, int(start * SR))
        b = min(N, int((start + length) * SR))
        piece = sfx[a:b]
        if not np.any(piece):
            continue
        music_band = rms_db(band(music_mono[a:b], low, high))
        effect_band = rms_db(band(piece.mean(axis=1), low, high))
        target = min(music_band + margin_db, cap_db)
        out[a:b] += piece * 10 ** ((target - effect_band) / 20)
    return out


def write_wav(path, x):
    x = np.clip(x, -1, 1)
    data = (x * 32767).astype("<i2").tobytes()
    with open(path, "wb") as f:
        f.write(b"RIFF")
        f.write((36 + len(data)).to_bytes(4, "little"))
        f.write(b"WAVEfmt ")
        f.write((16).to_bytes(4, "little"))
        f.write((1).to_bytes(2, "little"))
        f.write((2).to_bytes(2, "little"))
        f.write(SR.to_bytes(4, "little"))
        f.write((SR * 4).to_bytes(4, "little"))
        f.write((4).to_bytes(2, "little"))
        f.write((16).to_bytes(2, "little"))
        f.write(b"data")
        f.write(len(data).to_bytes(4, "little"))
        f.write(data)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="work/audio")
    args = parser.parse_args()
    os.makedirs(args.out, exist_ok=True)

    music = compose_music()
    # Leave real headroom; final loudness is set by ffmpeg's loudnorm on the mix.
    music *= 10 ** ((-20 - rms_db(music)) / 20)
    sfx = balance_sfx(music, compose_sfx())
    mix = music + sfx

    write_wav(os.path.join(args.out, "music.wav"), music)
    write_wav(os.path.join(args.out, "sfx.wav"), sfx)
    write_wav(os.path.join(args.out, "mix.wav"), mix)
    print(f"music {rms_db(music):.1f} dBFS rms, sfx {rms_db(sfx):.1f}, mix {rms_db(mix):.1f}; peak {20*np.log10(np.max(np.abs(mix))):.1f} dBFS")


if __name__ == "__main__":
    main()
